development:
  adapter: mysql2
  encoding: utf8
  database: fashion_development
  pool: 5
  username: root
  password: root

test: 
  adapter: mysql2
  encoding: utf8
  database: fashion_test
  pool: 5
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  database: fashion_production
  pool: 5
  username: root
  password: root
